name: Run E2E on PR

on:
    pull_request:
        branches:
            - main

jobs:
    check_labels:
        runs-on: 
            - ubuntu-latest
        outputs:
            e2e: ${{ steps.e2e.outputs.e2e }}
        steps:
        - id: check_breaking_change
        name: "Check 'PR: Breaking change' label exists"
        uses: docker://agilepathway/pull-request-label-checker:v1.0.103
        continue-on-error: true
        with:
            one_of: 'PR: Breaking change'
            repo_token: ${{ secrets.GITHUB_TOKEN }}

        - name: Standard e2e Branch
        run: echo "E2E=main" >> $GITHUB_ENV

        - name: Check for corresponding branch exists
        if: steps.check_breaking_change.outcome == 'success'
        continue-on-error: true
        uses: octokit/request-action@v2.x
        id: check-e2e-branch
        env:
            GITHUB_TOKEN: ${{ secrets.GPR_TOKEN }}
            with:
            route: GET /repos/{owner}/{repo}/branches/{branch}
            owner: AnhNg-GithubActions
            repo: e2e
            branch: ${{ github.head_ref || github.ref_name }}

        - name: Override with custom e2e Branch
            if:
                steps.check_breaking_change.outcome == 'success' && steps.check-e2e-branch.outcome
                == 'success'
            run: echo "E2E=${{ github.head_ref || github.ref_name }}" >> $GITHUB_ENV

        - name: Set e2e to output
            id: e2e
            run: echo "e2e=${{ env.E2E }}" >> $GITHUB_OUTPUT

    build-e2e-image:
        runs-on:
            - ubuntu-latest
        outputs:
            tag: ${{ steps.tag.outputs.tag }}
        steps:
            # - name: Set custom name
            # if: ${{  ( github.head_ref || github.ref_name )  != 'main' }}
            # run: echo "TAG=pr-${{github.run_id}}" >> $GITHUB_ENV

            # - name: Set standard name
            # if: ${{  ( github.head_ref || github.ref_name )  == 'main' }}
            # run: echo "TAG=latest" >> $GITHUB_ENV

            # - name: Set name as job output
            # id: tag
            # run: echo "tag=${{ env.TAG }}" >> $GITHUB_OUTPUT

            - uses: actions/checkout@v3
            id: checkout
            with:
                path: ./actions
                repository: AnhNg-GithubActions/app
                token: ${{ secrets.GITHUB_TOKEN }}

            - name: Build E2E for branch
            if: ${{  ( github.head_ref || github.ref_name )  != 'main' }}
            uses: ./actions/.github/actions/build-e2e-image
            with:
                version: ${{  ( github.head_ref || github.ref_name )  }}
                tag: ${{ env.TAG }}
                docker-hub-user: ${{ secrets.DOCKER-HUB-USER }}
                docker-hub-token: ${{ secrets.DOCKER-HUB-TOKEN }}
        needs: check_labels

    build-app-image:
        runs-on:
            - ubuntu-latest
        outputs:
            tag: ${{ steps.tag.outputs.tag }}
        steps:
            - name: Set custom name
            if: ${{  ( github.head_ref || github.ref_name )  != 'main' }}
            run: echo "TAG=pr-${{github.run_id}}" >> $GITHUB_ENV

            - name: Set standard name
            if: ${{  ( github.head_ref || github.ref_name )  == 'main' }}
            run: echo "TAG=latest" >> $GITHUB_ENV

            - name: Set name as job output
            id: tag
            run: echo "tag=${{ env.TAG }}" >> $GITHUB_OUTPUT

            - uses: actions/checkout@v3
            id: checkout
            with:
                path: ./actions
                repository: AnhNg-GithubActions/app
                token: ${{ secrets.GPR_TOKEN }}

            - name: Build APP for branch
            if: ${{  ( github.head_ref || github.ref_name )  != 'main' }}
            uses: ./actions/.github/actions/build-app-image
            with:
                version: ${{  ( github.head_ref || github.ref_name )  }}
                tag: ${{ env.TAG }}
                docker-hub-user: ${{ secrets.DOCKER-HUB-USER }}
                docker-hub-token: ${{ secrets.DOCKER-HUB-TOKEN }}
    

